spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: admin-service
          uri: lb://ADMIN-SERVICE
          predicates:
            - Path=/admin/**
        - id: student-service
          uri: lb://STUDENT-SERVICE
          predicates:
            - Path=/student/**
        - id: teacher-service
          uri: lb://teacher-service
          predicates:
            - Path=/teacher/**
      